#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart
