#!/usr/bin/env bash
#displays the content of the file /etc/passwd

exec 3< /etc/passwd

while IFS=':' read -r password uid gid gecos homedir shell;
do
    IFS=',' read -r name info <<< "$gecos"

    echo "The user $name is part of the group $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $uid $info"

done <&3

exec 3<&-
